   name: 手动触发刷步数240910

   on:
     push:
       branches: [master]
     pull_request:
       branches: [master]
     workflow_dispatch:
       inputs:
         user:
           description: '用户名'
           required: true
           default: ''
         pwd:
           description: '密码'
           required: true
           default: ''
         step:
           description: '步数'
           required: false
           default: '0'

   jobs:
     build:
       runs-on: ubuntu-latest

       steps:
       - uses: actions/checkout@v3.1.0

       - name: 缓存 Python 依赖
         uses: actions/cache@v3
         with:
           path: ~/.cache/pip
           key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
           restore-keys: |
             ${{ runner.os }}-pip-

       - name: 初始化 Python
         uses: actions/setup-python@v4.2.0
         with:
           python-version: '3.9'

       - name: 安装依赖
         run: |
           if [ -f requirements.txt ]; then
             pip install -r requirements.txt
           else
             pip install requests
           fi

       - name: 开始
         run: |
           user='${{ github.event.inputs.user }}'
           pwd='${{ github.event.inputs.pwd }}'
           step='${{ github.event.inputs.step }}'
           
           python3 main.py <<EOF
           ${user}
           ${pwd}
           ${step}
           EOF
