name: 刷步数

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # workflow_dispatch: # 手动触发
  schedule:
    - cron: 20 8 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v3.1.0
    - name: 初始化Python
      uses: actions/setup-python@v4.2.0
      with:
        python-version: '3.9'
    - name: 缓存 pip 包
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: 开始
      run: |
        pip install requests
        user='${{ secrets.USER }}'
        pwd='${{ secrets.PWD }}'
        step='${{ secrets.STEP }}'
        
        python3 main.py <<EOF
        ${user}
        ${pwd}
        ${step}
        EOF
