name: 刷步数19.30
##运行时间和步数：19.30	UTC11.30	STEP19=13624-16355
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # workflow_dispatch: # 手动触发
  schedule:
    - cron: 40 9,11 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    #if: github.event.repository.owner.id == github.event.sender.id#

    steps:
    - uses: actions/checkout@v3.1.0
    - name: 初始化Python
      uses: actions/setup-python@v4.2.0
      with:
        python-version: '3.9'
    - name: 开始
      run: |
        pip install requests
        user='${{ secrets.USER }}'
        pwd='${{ secrets.PWD }}'
        step='${{ secrets.STEP19 }}'
        
        python3 main.py <<EOF
        ${user}
        ${pwd}
        ${step}
        EOF
