name: 刷步数8.00
##运行时间和步数：8.00	UTC23.30	STEP7=3053-6166
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # workflow_dispatch: # 手动触发
  schedule:
    - cron: 6 0 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.1.0
    - name: 初始化Python
      uses: actions/setup-python@v4.2.0
      with:
        python-version: '3.9'
    - name: 开始
      run: |
        pip install requests
        pip install arrow
        user='${{ secrets.USER }}'
        pwd='${{ secrets.PWD }}'
        step='${{ secrets.STEP7 }}'
        
        python3 main.py <<EOF
        ${user}
        ${pwd}
        ${step}
        EOF
